# Generated by Django 2.2.13 on 2020-06-21 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.TextField(max_length=255)),
                ('pub_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('description', models.TextField(max_length=255)),
                ('icon', models.ImageField(blank=True, upload_to='icons/')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('votes_total', models.IntegerField(blank=True, default=1)),
                ('hunter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
